### ISSUE TITLE
Invalid CFBundleSupportedPlatforms value

### ISSUE THREAD

**Issue by DimICE** [SwiftyVK/SwiftyVK#100]
iTunes Store Operation Failed
ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/my.app/Frameworks/SwiftyVK.framework/SwiftyVK_resources_iOS.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by west0r** [comment]
Please fill issue template to give me more information
