### ISSUE TITLE
Won't build on swift 4

### ISSUE THREAD

**Issue by ursanotsomajor** [SwiftyVK/SwiftyVK#101]
Hello! Received several compiler errors like 

> 'allZeros' is unavailable: Use 0

telling about obsolete code. SwiftyVK Github page states it is ready for Swift 4, my project and pods are configured for Swift 4. 

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform version        | 10
 Xcode version           | 9
 Swift version           | 4
 SwiftyVK version        | 2.0.14
 Integration Method      | Cocoapods

**Comment by west0r** [comment]
Only SwiftyVK 3.x is swift 4 compatible and 2.x is not. You can use 3.x version as swift 4 pod, or older versions as swift 3 pod. But these versions have a different public interface.

**Comment by west0r** [comment]
Done
