### ISSUE TITLE
LongPoll forcedStop

### ISSUE THREAD

**Issue by xsimplex** [SwiftyVK/SwiftyVK#104]
### Description

Возможно, я что-то делаю не так, но у меня никак не получается работать с LongPoll сервером. Всегда возвращает `.forcedStop`

Например, беру Ваш пример и меняю метод авторизации на:
```swift
class func authorize() {
        VK.sessions?.default.logIn(
            onSuccess: { info in
                print("SwiftyVK: success authorize with", info)
                
                VK.sessions?.default.longPoll.start {
                    for event in $0 {
                        switch event {
                        case let .type4(data):
                            let json = JSON(data)
                            print( json )
                        case .forcedStop:
                            print("Forced stop")
                        default:
                            break
                        }
                    }
                }
            },
            onError: { error in
                print("SwiftyVK: authorize failed with", error)
            }
        )
    }
```
Я так думаю, что после успешной авторизации должна начаться "прослушка" longpoll сервера и при поступлении нового сообщения должен печататься наш json.
Я что-то не так делаю?

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 11.0
 Xcode version           | 9.0
 Swift version           | 4.0
 SwiftyVK version        | 2.0.0
 Integration Method      | cocoapods
 
 ### Checklist
 
* [+] I have looked and not find decision at [README.md](./README.md)
* [+] I have looked and not find decision at [Example project](./Example)
* [+] I have not find duplicates of this issue on [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [+] I have full filled out this issue template

**Comment by west0r** [comment]
Сейчас не могу посмотреть. Нужен стектрейс откуда ошибка пришла.

**Comment by west0r** [comment]
Локализовал. Будет в следующем обновлении.
