### ISSUE TITLE
Авторизация по токену

### ISSUE THREAD

**Issue by Amekill** [SwiftyVK/SwiftyVK#105]
### Description

После авторизации по токену методом `VK.sessions?.default.logIn(rawToken: String, expires: TimeInterval)` блок State всегда отдает статус инициации.

Пример: я сменил пароль и новый токен закинул в logIn(rawToken: token, expires: 0), перезапустил приложение и получаю State = initiated, хотя если не перезапускать приложение, то все запросы отсылались нормально.

И можно ли как-то подменять токен? Сейчас для его смены надо делать выход и потом уже авторизацию по токену.

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform version        | 11.1
 Xcode version           | 9.1
 Swift version           | 4
 SwiftyVK version        |3.0.2
 Integration Method      | carthage

**Comment by west0r** [comment]
Проблема со сбросом статуса после перезагрузки уже поднималась в #103. Пока токен не загружен из кейчейна сессия имеет состояние `initiated `. Фикс сделаю в ближайшем обновлении.

Подменять токен нельзя. `logIn(rawToken:, expires: )` - вырожденный способ авторизации, который не должен активно использоваться. 

В случае авторизации другим способом при невалидности токена должна происходить процедура его обновления. Если сейчас это не так - напишите здесь, я буду смотреть.

**Comment by west0r** [comment]
Закрываю как дубликат. Дальнейшее обсуждение будет в #103.
