### ISSUE TITLE
Проблема при авторизации в приложении VKApp

### ISSUE THREAD

**Issue by dT231** [SwiftyVK/SwiftyVK#107]
### Description

Во время авторизации, когда вызывается 
`VK.sessions?.default.logIn`
открывается приложение с ошибкой 

> _{"error":"invalid_request" , "error_description":"sdk not set up, check application settings"}_

P.S. Если выхожу из VKApp  и захожу обратно в свое и заполняю (oAuth WebView) там логин и пароль(как было в предыдущих версиях SwiftyVk) тогда все ок.

VKApp version : 2.15.2

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform version        | 10.3
 Xcode version           | 9.1
 Swift version           | 4
 SwiftyVK version        | 3.0.2
 Integration Method      | cocoapods
VKApp version | 2.15.2
 
 ### Checklist
 
 Set [x] in box if you checked this:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and not find decision at [Example project](./Example)
* [x] I have not find duplicates of this issue on [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ ] I made an understandable short title
* [ ] I made an exhaustive description
* [ ] I completely described the environment 
* [ ] I have full filled out this issue template
* [ ] I use english language

**Comment by west0r** [comment]
Текст ошибки говорит "sdk not set up, check application settings". перове что приходит в голову - bundleId не прописан в настройках приложения. Вот как сделано для демо -
![screen shot 2017-11-05 at 13 57 50](https://user-images.githubusercontent.com/8268115/32414136-5c7be86c-c231-11e7-8a77-f2a46eac013e.png)

**Comment by dT231** [comment]
Да сделал, ситуация поменялась, но глобально не решилась. Сейчас после открытия VKApp и после согласия на доступ к аккаунту VK, он закрывает popup доступа к аккаунту, но остается в VKApp и не завершает процесс авторизации.
P.S. AppDelegate сделал так же как в примере

**Comment by dT231** [comment]
Спасибо. Проблема решена
