### ISSUE TITLE
This application is modifying the autolayout engine from a background thread

### ISSUE THREAD

**Issue by dT231** [SwiftyVK/SwiftyVK#113]
После выполнения 

> vkTokenCreated()

 происходит 

> This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

---

### Description

Describe the issue in detail here

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 10.3
 Xcode version           | 9.0
 Swift version           | 4.0
 SwiftyVK version        | 3.0.5
 Integration Method      |cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ ] I made an understandable short title and exhaustive description
* [x] I attach stack traces or errors description
* [ ] I completely describe the environment 
* [ ] I have full filled out this issue template

**Comment by west0r** [comment]
Проблема происходит даже без показа вебвью?
В демо проекте точно смотрели и воспроизвели поведение?

**Comment by dT231** [comment]
Прости за долги ответ, проблема была в моем коде.
