### ISSUE TITLE
У NewsFeed.get отсутствует параметр filters

### ISSUE THREAD

**Issue by fuwaneko** [SwiftyVK/SwiftyVK#116]
См. https://vk.com/dev/newsfeed.get
![image](https://user-images.githubusercontent.com/34433/33717907-99e8c4d0-db96-11e7-803c-7a81de70c172.png)

**Comment by west0r** [comment]
Добавлю, как будет время.
В качестве временного решения можно использоавть Custom метод, где параметры - строки.
