### ISSUE TITLE
Бесконечный токен

### ISSUE THREAD

**Issue by dT231** [SwiftyVK/SwiftyVK#121]
### Description

При авторизации через vkApp, примерно через сутки при запуске приложения вызывается tokenCreated(), но запросы уже не действуют, я так понимаю из-за недействительного токена.
Можно ли как то автоматически пересоздать токен или сделать его бесконечно действующим? Спасибо. 
### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios 
 Platform version        | 10.3.3
 Xcode version           | 9
 Swift version           | 4.0
 SwiftyVK version        | 3.1.2
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ ] I made an understandable short title and exhaustive description
* [ ] I attach stack traces or errors description
* [ ] I completely describe the environment 
* [ ] I have full filled out this issue template

**Comment by west0r** [comment]
В документации VK API как раз описан скоуп прав для бесконечного токена
<img width="937" alt="screen shot 2017-12-30 at 09 42 56" src="https://user-images.githubusercontent.com/8268115/34451951-f83d887a-ed45-11e7-8c44-aea77026538a.png">
Но помимо этого должна работать система получения нового токена по истечении текущего.

**Comment by west0r** [comment]
Сейчас, воспроизводя подобную ситуацию, я наблюдаю успешное обновление токена.

Пожалуйста, опишите подробнее, что происходит. 
Это происходит сразу после открытия приложения? 
Открывается ли приложение для авторизации? 
Вызывается ли `vkTokenUpdated`?
Первый запрос и запрос после обновления имеют один и тот же токен или разные?

Любая дополнительная информация не помешает.

**Comment by dT231** [comment]
После того как запускаю приложение:
`VKDELEGATE INIT
token created in session rfeSAKm3aLGmJ1mNNkla with info ["user_id": "425845160", "email": "k-rashidova@list.ru", "access_token": "4a0071f4a43ad82a0b31bbc95a64ddcec4decd2cf5cc18ed65a90d0f5ecc8574f4f139f5a33dff30f0531", "expires_in": "86400"]
setInfoFromVK start
VK PARAMETERS : ["user_id": "425845160", "email": "k-rashidova@list.ru", "access_token": "4a0071f4a43ad82a0b31bbc95a64ddcec4decd2cf5cc18ed65a90d0f5ecc8574f4f139f5a33dff30f0531", "expires_in": "86400"]
viewDidLoad LogInSecondViewController
SwiftyVK: getVkFriendsList failed with 
unknown`

> Открывается ли приложение для авторизации
нет

> Вызывается ли vkTokenUpdated
похоже что нет.

p.s В предыдущей версии(или 2 версии назад) было все ок.

**Comment by dT231** [comment]
Еще иногда он зацикливается в переходе между мои приложением и vkapp.

**Comment by west0r** [comment]
Спасибо за информацию. В ближайшее время посмотрю в чем может быть дело.
