### ISSUE TITLE
Понизить MACOSX_DEPLOYMENT_TARGET в библиотеке до macOS 10.10

### ISSUE THREAD

**Issue by dattk** [SwiftyVK/SwiftyVK#123]
ожидается "Requirements macOS 10.10 +"

но при установке через Сarthage и сборки библиотеки получаем 10.11+

В Library/SwiftyVK.xcodeproj/project.pbxproj закралось:
"MACOSX_DEPLOYMENT_TARGET = 10.11;"

Просьба понизить.

**Comment by dattk** [comment]
попробовал собрать проект с MACOSX_DEPLOYMENT_TARGET = 10.10,
но получается в нём используются функции и свойства @available(OSX 10.11, *), жаль.

**Comment by west0r** [comment]
Повысил, так как до 10.11 у NSCollectionView ужасное API и очень не хотелось его использовать.
Не думал, что 10.10 еще настолько актуальна.
Если есть сильная необходимость именно в 10.10, то можно перейти на старое API NSCollectionView. Боюсь, что у меня сейчас нет необходимость и времени на это, но буду рад любой помощи.

Второй вариант решения - отключить шаринг для 10.10. Тогда проект будет работать за исключением этой фичи.

**Comment by west0r** [comment]
В общем, сделал для 10.10 версию без шаринга.
