### ISSUE TITLE
ошибка при вызове ShareDialog 

### ISSUE THREAD

**Issue by Sunrizzin** [SwiftyVK/SwiftyVK#125]
Добрый день!

После успешной авторизации в приложении пытаюсь вызвать ShareDialog следующим образом:

```
 VK.sessions.default.share(ShareContext(text: Test message", images: [], link: ShareLink(title: "test url", url: URL(string: "http://vk.com")! ), canShowError: true ), onSuccess: { (data) in
                    print(data)
                }) { (error) in
                    print(error)
                }
```

Но получаю ошибку следующего содержания:

`Unknown class _TtC8SwiftyVK18ShareControllerIOS in Interface Builder file.`

Пожалуйста, подскажите в чём может быть проблема? 
В документации и в гугле ничего по этому поводу не нашёл.

**Comment by west0r** [comment]
Пожалуйста, заполните isuue template, чтобы у меня было больше данных для понимания проблемы.

**Comment by Sunrizzin** [comment]
# 🚫 **Ошибка вызова ShareDialog** 🚫

🚫 Thanks for using SwiftyVK.

🚫 Support for this project takes a lot of my time. 

🚫 Please, be attentive, fill template and delete this title to let me cope with the issue faster. 

🚫 Issues without filled description, environment and checklist ***will be closed without any comments***

🚫 Thank you for understanding.

---

### Description

При попытке вызова ShareDialog:
```
 VK.sessions.default.share(ShareContext(text: Test message", images: [], link: ShareLink(title: "test url", url: URL(string: "http://vk.com")! ), canShowError: true ), onSuccess: { (data) in
                    print(data)
                }) { (error) in
                    print(error)
                }
```

возникает ошибка: Unknown class _TtC8SwiftyVK18ShareControllerIOS in Interface Builder file.

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform version        | 11
 Xcode version           | 9.2
 Swift version           | 4.0
 SwiftyVK version        | 3.1.3
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x] I made an understandable short title and exhaustive description
* [x] I attach stack traces or errors description
* [x] I completely describe the environment 
* [x] I have full filled out this issue template

**Comment by west0r** [comment]
В ветке develop новая версия с фиксом

**Comment by Sunrizzin** [comment]
Благодарю!
