### ISSUE TITLE
Unknown class _TtC8SwiftyVK16WebControllerIOS in Interface Builder file.

### ISSUE THREAD

**Issue by merlinbbc** [SwiftyVK/SwiftyVK#128]
Unknown class _TtC8SwiftyVK16WebControllerIOS in Interface Builder file. 

Вот такая ошибка. Не знаю как исправить. iOS - 11.3, Xcode - Version 9.3 (9E145)

**Comment by west0r** [comment]
Проблема в сочетании CocoaPods + static library + storyboards в отдельном от кода контроллера бандле. Пришлось откатиться на динамическую либу.
