### ISSUE TITLE
ShareContext don't post and dont have error too

### ISSUE THREAD

**Issue by saroar** [SwiftyVK/SwiftyVK#131]
### Description

Describe the issue in detail here

i am trying to share from my ios app here is my code 

no error from this 
```
guard let pic = PerfectLocalAuth.userdetails["picture"] as? String else {
            return
        }
        
        if let url = URL(string: pic) {
            let task = URLSession.shared.dataTask(with: url, completionHandler: { data, response, error in
                if let data = data {
                    VK.sessions.default.share(
                        ShareContext(
                            text: "This post made with #SwiftyVK 🖖🏽",
                            images: [
                                ShareImage(data: data, type: .jpg)
                            ],
                            link: ShareLink(
                                title: "Follow the white rabbit", // Link description
                                url: URL(string: "localhost")! // URL to site
                            )
                        ),
                        onSuccess: { response in
                            print(response)
                    },
                        onError: { error in
                            print(error)
                    })
                }
            })
            task.resume()
}
```

here is my `func`
```
func postToFeedForVK() {
        VK.API.Users.get([
            .filters: "post",
            .returnBanned: "0",
            .fields: "first_name,last_name,photo_50,gid,name,photo"
            ])
            .onSuccess {

                do {
                    let response = try JSONSerialization.jsonObject(with: $0)
                    print(response)

                } catch {
                    print(error)
                }
            }.send()
        } < this func working that mean i have token and session 

```

i have already Oauth2 install so I get this
so do this 
```
/* ==========================================================
     VK
     ========================================================== */
    @IBAction func doVkOAuth(_ sender: Any) {
        let service = "Vk"
        
        guard var parameters = services[service] else {
            print("\(service) not configured")
            return
        }
        
        let oauthswift = OAuth2Swift(
            consumerKey:    parameters["consumerKey"] ?? "",
            consumerSecret: parameters["consumerSecret"] ?? "",
            authorizeUrl:   "https://oauth.vk.com/authorize",
            accessTokenUrl: "https://oauth.vk.com/access_token",
            responseType:   "code"
        )
        
        self.oauthswift = oauthswift
        oauthswift.authorizeURLHandler = getURLHandler()
        let state = generateState(withLength: 20)
        _ = oauthswift.authorize(
            withCallbackURL: URL(string: "\(PerfectLocalAuth.host)/api/v1/oauth/return/vk")!,
            scope: "profile, city, photos, email, friends",
            state: state,
            success: { credential, response, parameters in
                print("credential.oauthToken", credential.oauthToken)
                
                // send upgrade user signal to Perfect OAuth2 Server
                let accessToken = credential.oauthToken
                
                do {
                    try VK.sessions.default.logIn(rawToken: accessToken, expires: TimeInterval(0)) *******
                } catch {
                    print("VK.sessions.default.logIn rawToken error")
                }
```

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform version        | 11.3
 Xcode version           | exact version e.g. 9.3.1
 Swift version           | exact version e.g. 4.1
 SwiftyVK version        | exact version3.1.5
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x ] I have looked and not find decision at [README.md](./README.md)
* [x ] I have looked and reproduce this behaviour in [Example project](./Example)
* [ x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x ] I made an understandable short title and exhaustive description
* [x ] I attach stack traces or errors description
* [ x] I completely describe the environment 
* [x ] I have full filled out this issue template

**Comment by saroar** [comment]
how i am trying something like this
```
guard
            let pathToImage = Bundle.main.path(forResource: "278", ofType: "png"),
            let data = try? Data(contentsOf: URL(fileURLWithPath: pathToImage)),
            let link = URL(string: "https://en.wikipedia.org/wiki/Hyperspace")
            else {
                print("Can not find testImage.png")
                return
        }
        
        VK.sessions.default.share(
            ShareContext(
                text: "This post made with #SwiftyVK 🖖🏽",
                images: [
                    ShareImage(data: data, type: .jpg),
                    ShareImage(data: data, type: .jpg)
                ],
                link: ShareLink(
                    title: "Follow the white rabbit",
                    url: link
                )
            ),
            onSuccess: { print("SwiftyVK: successfully shared with \n \(JSON($0))") },
            onError: { print("SwiftyVK: share failed with \n \($0)") }
        )
```

error is 
```image not uploaded with error: jsonNotParsed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.})
image not uploaded with error: jsonNotParsed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.})```

**Comment by saroar** [comment]
also getting an error when trying to upload photos 

```
class func uploadPhoto() {
        guard
            let pathToImage = Bundle.main.path(forResource: "matroshka", ofType: "png"),
            let data = try? Data(contentsOf: URL(fileURLWithPath: pathToImage))
            else {
                print("Can not find testImage.png")
                return
        }
        
        let media = Media.image(data: data, type: .png)
        
        VK.API.Upload.Photo.toWall(media, to: .user(id: "\(PerfectLocalAuth.vkUserId)"))
            .onSuccess { print("SwiftyVK: upload successed with \n \(JSON($0))") }
            .onError { print("SwiftyVK: upload failed with \n \($0)")}
            .onProgress { print($0) }
            .send()
    }
    
    func postToFeedForVK() {
        HeventVC.uploadPhoto()
}
```

**Comment by west0r** [comment]
Hello. Thanks for using SwiftyVK.

I read your comments but issue looks strange and I can't reproduce it. Please make following steps:

1. Try to share post or photo from example application in this repository.  (You need change App id and bundle id in example for yours) What's the result? I am getting valid success response.

2. Be sure that `PerfectLocalAuth.vkUserId` or other strings are not optional because optional strings in construction like `"\(PerfectLocalAuth.vkUserId)"` can be `Optional(1234567890)` and this is not valid data for request.

3. Try to set breakpoint in `Response.swift line 9` and print string from rawData or sniff traffic with any traffic sniffer (for example Charles).

**Comment by west0r** [comment]
It decided only by user in post preferences UI because user can doesn't link own facebook profile to VK or want to share post to other social networks.

**Comment by saroar** [comment]
can I also delete this post
i should to delete from my app after 4 hours its even for 4 hours only 
how i can do it 
http://prntscr.com/jo6cvd
its working now

**Comment by west0r** [comment]
SwiftyVK doesn't provide ability to share posts to other social networks because it's library only for VK. But VK does if user link own Facebook/Twitter account to VK in site preferences and allows sharing. Only user can decide when and what share to other networks, you can't.

**Comment by saroar** [comment]
can I also delete this post
i should to delete from my iOS app after 4 hours its even for 4 hours only
how i can do it

**Comment by west0r** [comment]
You can save post info after sharing and delete this post lately with https://vk.com/dev/wall.delete method.

**Comment by saroar** [comment]
when i try to with real device and click share button it goes to open my iPhone app then ask me permission after i get permission from iPhone vk app it doesn't redirect to my app this is 1a st problem 
2nd when i go back my original app it shows me login screen then i have to login and share my post 

why its open VK app if my own app login screen? 
please try your self in your own iPhone and let me know thanks

**Comment by west0r** [comment]
Please read carefully [this README section](https://github.com/SwiftyVK/SwiftyVK#official-vk-application) set all schemes  and bundle id right
