### ISSUE TITLE
Blank (White) page at second day

### ISSUE THREAD

**Issue by snake302** [SwiftyVK/SwiftyVK#133]
### Description

Привет! Ситуация следующая - на второй день после авторизации выкидывает просто белую страницу в момент инициализации api и приложение просто становится недоступно. 

1) Если удалить приложение с устройства, установить, авторизоваться -> работает 1 день, на следующий день белая страница 
2) Если отключить SwityVK - то приложение продолжает работать

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform version        | 11
 Xcode version           | 9.3
 Swift version           | 4.0
 SwiftyVK version        | 3.1.6
 Integration Method      | cocoapods
 
  ### Checklist
 
 
* [X ] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [X] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [X] I made an understandable short title and exhaustive description
* [X] I attach stack traces or errors description
* [X] I completely describe the environment 
* [X] I have full filled out this issue template

**Comment by west0r** [comment]
Привет. Чтобы разобраться в проблеме мне нужны дополнительные данные. Пожалуйста, попробуй ответить на следующие вопросы:

1. Какие права у токена, есть ли `.offline`?
2. Белый экран приложения или именно модальный от SwiftyVK? 
3. Что происходит в `VKDelegate` в методах `vkTokenCreated` `vkTokenUpdated` `vkTokenRemoved` `vkNeedToPresent` и в каком порядке?
4. В какие моменты в приложении вызываются `setUp` и `logIn`
5. Точно ли нет дедлоков при обращении к библиотеке?
6. Установлено ли приложение VK и через что происходит логин, через него или web view?

Если есть демка с воспроизведением данного поведения, то было бы неплохо прилинковать ее сюда.

**Comment by west0r** [comment]
И еще один важный вопрос, в момент авторизации/посылки первого запроса вьюконтроллер из которого будет показан контроллер авторизации уже на экране?

**Comment by snake302** [comment]
Косяк на моей стороне был -> как раз смена порядка расположения все починила

**Comment by west0r** [comment]
@snake302 в чем была проблема? Возможно, можно как-то этот кейс покрыть на уровне библиотеки)

**Comment by snake302** [comment]
Я сначала в didFinishLaunchingWithOptions указывал на какой экран перебрасывать и после этого уже выполнял VK.setUp, после того как поменял порядок сперва на VK.setUp и после выбор экрана все пофиксилось)

**Comment by west0r** [comment]
То есть в делегате возвращался не текущий top view controller?
