### ISSUE TITLE
VK.sessions.default.state == .initiated после попытки оплаты через Яндекс деньги

### ISSUE THREAD

**Issue by borovoff** [SwiftyVK/SwiftyVK#138]
### Description
Использую тестовый пример пополнения кошелька с карты через https://github.com/yandex-money/yandex-money-sdk-objc.

После нажатия кнопки pay (можно не заполнять данные) и закрытия, открытия приложения VK.sessions.default.state изменяется с .authorized на .initiated. С чем это может быть связано?

Можно ли использовать в этом случае VK.sessions.default.logIn(rawToken: token, expires: 0), где token - токен, сохраненный при предыдущем входе?
В этом случае срабатывает vkTokenCreated с пустым info, это нормально?
Причем далее, если открыть-закрыть приложение он также остается пустым, хотя VK.sessions.default.state == .authorized

Спасибо. 😌

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 11.2
 Xcode version           | 9.4.1
 Swift version           | 4.1
 SwiftyVK version        | 3.1.9
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x ] I have looked and not find decision at [README.md](./README.md)
* [ x] I have looked and reproduce this behaviour in [Example project](./Example)
* [ x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ x] I made an understandable short title and exhaustive description
* [ x] I attach stack traces or errors description
* [ x] I completely describe the environment 
* [ x] I have full filled out this issue template

**Comment by west0r** [comment]
Привет. Спасибо за фидбек. Сейчас нет возможно посмотреть что с яндексом происходит, но мне бы очень помог демо-проект с воспроизведением этой ошибки

**Comment by borovoff** [comment]
Я правильно понимаю, что желательно, чтобы я дополнил твой пример из этого проекта примером яндекса и поделился?

**Comment by west0r** [comment]
Можно сделать пустой проект с интеграцией SeiftyVK и yandex-money-sdk-objc и вопроизводится проблема)

**Comment by borovoff** [comment]
Пожалуйста: https://github.com/borovoff/SwiftyVKYandexMoneyLove

**Comment by west0r** [comment]
Такое поведение получается из-за возникновения двух факторов
SwiftyVK хранит токен в кейчейне
ViewController из примера yandex-money-sdk-objc сносит весь кейчейн без разбора [вот на этой вот строчке](https://github.com/yandex-money/yandex-money-sdk-objc/blob/1f3af121e5b243bc02a5bfaad41f9af5fe292252/Example/ios/Example1/YandexMoneySDK-example/ViewController.m#L81).

Итого: кейчейн снесен, токен удален, авторизоваться не можем. Если закоментить строку с очисткой кейчейна, то все будет работать. По крайней мере в демо проекте, но не факт, что в проде, так как подобный код у них встречается и в самой либе.

Заведу им issue на этот счет. Несмотря на то, что они не обновляли либу больше полугода, надеюсь пофиксят быстро.
