### ISSUE TITLE
RxSwift support

### ISSUE THREAD

**Issue by SeRG1k17** [SwiftyVK/SwiftyVK#139]
What do you think, if we add support RxSwift?

I think need one update:
```swift
public final class VK: **NSObject** { //... }
```

After we can make call as:
```swift
VK.API.Wall.get(Parameters).rx.send() //type: Observable<Data>
//etc.
```

**Comment by west0r** [comment]
Thank You for using SwiftyVK and your feedback)

Do You wanna add RxSwift as a dependency inside SwiftyVK?
Why You can't use SwiftyVK sending syntax? In my opinion, it's similar to Promises / Rx and very conveniently.

I'm not Rx fan and don't wanna add new dependencies without without much need

**Comment by west0r** [comment]
@SeRG1k17, I have not received a response from you in a month. So, I close this issue. If you have something to answer, you can reopen it again.

Best regards)
