### ISSUE TITLE
Authorization crashes on macOS Mojave

### ISSUE THREAD

**Issue by usr-sse2** [SwiftyVK/SwiftyVK#142]
### Description

In the example project, log in crashes after dismissing the web view. There is an assertion in WebKit that checks if it's called from main thread, but it's called not from the main thread. I wasn't able to fix it easily, because of the semaphore.

_(Really it stops at previous instruction (at 0x00007fff4a525175 `int 3` with EXC_BREAKPOINT, this stacktrace is after clicking Continue)._
```
* thread #2, queue = 'SwiftyVK.sessionQueue', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00007fff4a525176 WebKit`WebKit::TiledCoreAnimationDrawingAreaProxy::~TiledCoreAnimationDrawingAreaProxy() + 90
    frame #1: 0x00007fff94f8fac0 WebKit`vtable for WebKit::TiledCoreAnimationDrawingAreaProxy + 16
    frame #2: 0x00007fff4a3624a4 WebKit`WebKit::TiledCoreAnimationDrawingAreaProxy::~TiledCoreAnimationDrawingAreaProxy() + 14
    frame #3: 0x00007fff4a6083df WebKit`WebKit::WebPageProxy::resetState(WebKit::WebPageProxy::ResetStateReason) + 109
    frame #4: 0x00007fff4a35de2e WebKit`WebKit::WebPageProxy::close() + 380
    frame #5: 0x00007fff4a744531 WebKit`-[WKWebView dealloc] + 57
    frame #6: 0x00007fff678647c2 libobjc.A.dylib`(anonymous namespace)::AutoreleasePoolPage::pop(void*) + 726
    frame #7: 0x00000001012f57dc libdispatch.dylib`_dispatch_last_resort_autorelease_pool_pop + 27
    frame #8: 0x00000001012fe923 libdispatch.dylib`_dispatch_lane_invoke + 563
    frame #9: 0x0000000101309f6c libdispatch.dylib`_dispatch_workloop_worker_thread + 691
    frame #10: 0x0000000101370058 libsystem_pthread.dylib`_pthread_wqthread + 409
    frame #11: 0x000000010136fe51 libsystem_pthread.dylib`start_wqthread + 13
```

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | osx
 Platform version        | 10.14
 Xcode version           | 10.0
 Swift version           | 4
 SwiftyVK version        | 3.1.9
 Integration Method      | manually
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x] I made an understandable short title and exhaustive description
* [x] I attach stack traces or errors description
* [x] I completely describe the environment 
* [x] I have full filled out this issue template

**Comment by west0r** [comment]
Ок, посмотрю что там в ближайшее время

**Comment by west0r** [comment]
@usr-sse2, I fixed it)

**Comment by usr-sse2** [comment]
@west0r, Спасибо, теперь работает)
