### ISSUE TITLE
'CFBundleSupportedPlatforms' in the Info.plist

### ISSUE THREAD

**Issue by saroar** [SwiftyVK/SwiftyVK#149]
ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/AddaIOS.app/Frameworks/SwiftyVK.framework/SwiftyVK_resources_iOS.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

i just update today 4.2  and getting this iusue 
### Description

Describe the issue in detail here

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx
 Platform version        | exact version e.g. 0.14.1 
 Xcode version           | exact version e.g. 10.0
 Swift version           | exact version e.g. 4.2
 SwiftyVK version        | exact version e.g. 2.0.0
 Integration Method      | e.g. carthage/cocoapods/manually
 
please check this link cant upload my app into app store http://prntscr.com/lmnsf4

**Comment by west0r** [comment]
I fixed it in the latest release (3.2)
