### ISSUE TITLE
Получить access_token если уже зарегестрировался

### ISSUE THREAD

**Issue by akantsevoi** [SwiftyVK/SwiftyVK#151]
Здравствуйте,  спасибо большое за библиотеку, очень хорошая работа.

Возник вопрос, я уже залогинился и получил токен, но не сохранил его нигде.
Убил приложение и пробую логинится заново, могу получить статус зарегестрирован/нет. Но не могу получить сам токен из апишки, без того, чтобы пабликом не сделать token поле в SessionImpl.

Подскажите, пожалуйста, может я что-то не так делаю?

Спасибо

**Comment by west0r** [comment]
Привет. Можно ли уточнить, с какой целью нужно забрать токен из библиотеки? Так как SwiftyVK полностью берет на себя работу с VK API, то доступ к токену не предоставляет)

**Comment by akantsevoi** [comment]
Так наша система устроена, что для создания пользователя засылается токен он через вк проверяется и если все ок - создается пользователь с нашими токенами. Соответственно мне нужен токен соц сети и при этом короткоживущий(это одна из причин, почему я решил не использовать официальный сдк)

**Comment by akantsevoi** [comment]
Вообще как ты смотришь на то, чтобы сделать пабликом доступ к токену? Например унаследовать `Session` от `TaskSession` или поле пабликом? Я закину пулл-реквест

**Comment by west0r** [comment]
Довольно странный флоу и я до конца не понял зачем так нужно, но я не против.

`TaskSession`. - внутренний протокол.
`Session ` - внешний. 
В него нужно добавить `var token: Token? { get }`, так как токен доступен только для чтения. Еще одно ограничение связано с тем, что токен доступен только когда пользователь авторизован и тут можно наткнуться на nil, если он истек, например.

Можно, кстати, подписаться на эвенты `vkTokenCreated` `vkTokenUpdated`. Там в словаре `info` должен прилетать токен.

**Comment by west0r** [comment]
Closed in #152

**Comment by djdance** [comment]
Прошу прощения за нубский вопрос, но я так и не понял, где взять ID юзера и его токен. 
Конечно, их можно ловить в _vkTokenCreated(for sessionId: String, info: [String : String])_ и сохранять вручную, но надо ли, если это есть напрямую? 

спасиб.

**Comment by djdance** [comment]
ага, нашёл
VK.sessions.default.accessToken?.info["access_token"]
VK.sessions.default.accessToken?.info["user_id"]
