### ISSUE TITLE
Отсутствует параметр filter [wall.get] 

### ISSUE THREAD

**Issue by Holofox** [SwiftyVK/SwiftyVK#155]
![2019-01-23 23 19 03](https://user-images.githubusercontent.com/19191492/51627914-65b48c80-1f65-11e9-9181-2415bab7dac6.png)

См. https://vk.com/dev/wall.get

**Comment by west0r** [comment]
Спасибо за информацию, посмотрю в ближайшее время. Если хочется быстрее, то можно слать кастомные запросы с кастомными параметрами или сделать PR с добавлением параметра (файл Parameters.swift)
