### ISSUE TITLE
SwiftVKState.plist couldn't be opened

### ISSUE THREAD

**Issue by Misterion777** [SwiftyVK/SwiftyVK#157]
### Description

Added URL schemes in Info.plist
VKDelegate implemented as in Example. 
Added initialization to AppDelegate as in Example.

On first call VK.session.default.logIn()  there is a error:
**Error Domain=NSCocoaErrorDomain Code=260 "The file "SwiftyVKState.plist" couldn't be opened because there is no such file."**

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 12.0
 Xcode version           | 10.1
 Swift version           | 4.2
 SwiftyVK version        | 3.3.1
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [ x] I have looked and not find decision at [README.md](./README.md)
* [x ] I have looked and reproduce this behaviour in [Example project](./Example)
* [x ] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x ] I made an understandable short title and exhaustive description
* [ x] I attach stack traces or errors description
* [ x] I completely describe the environment 
* [ x] I have full filled out this issue template

**Comment by west0r** [comment]
Hello @Misterion777. Thank you for report. 
It's normal, If it happens only at first launch, because library tries to read not yet existing file.
It will be created after first logging in and the error will be gone.

I'll fix this error message in nearest pull request.

Please, let me know If it happens every time.
