### ISSUE TITLE
market.getById

### ISSUE THREAD

**Issue by ffoeta** [SwiftyVK/SwiftyVK#158]
### Description

market.getById method expects request to have 
"item_ids" field, which is not included into "Parameter" enum
There is only "item_id" which causes:

api(SwiftyVK.ApiError(code: 100, message: "One of the parameters specified was missing or invalid: item_ids is undefined", requestParams: ["item_id": "-124527492_250407", "lang": "en", "oauth": "1", "method": "market.getById", "v": "5.92", "https": "1"], otherInfo: [:]))

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx
 Platform version        | exact version e.g. 8.0
 Xcode version           | exact version e.g. 9.0
 Swift version           | exact version e.g. 3.0
 SwiftyVK version        | exact version e.g. 2.0.0
 Integration Method      | e.g. carthage/cocoapods/manually
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x] I made an understandable short title and exhaustive description
* [-] I attach stack traces or errors description
* [-] I completely describe the environment 
* [-] I have full filled out this issue template

**Comment by west0r** [comment]
Hello @ffoeta. I'll add this parameter in next release.

You can read how to add it by himself in the future - https://github.com/SwiftyVK/SwiftyVK/wiki/I-can't-find-some-API-method-or-parameter-in-library
