### ISSUE TITLE
Проблема с загрузкой WebView

### ISSUE THREAD

**Issue by st-small** [SwiftyVK/SwiftyVK#163]
### Description
При выборе пользователем способа авторизации "через Вк", пушу контроллер, в котором презентится VKViewController (в методе vkNeedToPresent(viewController: VKViewController)). Показывается спиннер с загрузкой WebView, дальше ничего не происходит. Если в этом методе создать vc, на него положить VKViewController и презентить уже этот вьюконтроллер, все отлично отображается и загружается, но я не могу отловить нажатие пользователем кнопки "Отмена", чтобы закрыть презентованный экран. Подскажите, пожалуйста, кто как сталкивается с данной проблемой?!

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                           | iOS
 Platform version              | 12.1 - 12.2
 Xcode version                  | 10.2.1
 Swift version                    | 4.2
 SwiftyVK version             | 3.4.0
 Integration Method         | cocoapods
 
  ### Checklist
* [*] I have looked and not find decision at [README.md](./README.md)
* [*] I have looked and reproduce this behaviour in [Example project](./Example)
* [*] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [*] I made an understandable short title and exhaustive description
* [*] I attach stack traces or errors description
* [*] I completely describe the environment 
* [*] I have full filled out this issue template

![Simulator Screen Shot - iPhone SE - 2019-06-11 at 19 01 43](https://user-images.githubusercontent.com/1850189/59292461-d1359700-8c85-11e9-9d71-5222679a6e80.png)

**Comment by st-small** [comment]
После тщательного анализа, решение все-таки нашел, но сомневаюсь в нем, очень хотелось бы услышать еще мнения. Архитектура моего приложения основана на паттерне "Координатор", получается, что при выборе метода авторизации, пользователь выбирает "вк", открывается (координатором пушится VkAuthController), в котором реализован метод VK.sessions.default.logIn. Этот метод я вызывал во viewDidLoad синхронно... При этом, в VKDelegateExample вызывался метод vkNeedToPresent(viewController: VKViewController), в котором брался "самый верхний контроллер" (на который мы презентим WebView)

**Comment by west0r** [comment]
@st-small, извиняюсь, что не смог оперативно отреагировать. Да, проблема и решение похожи на правду. Презентить нужно из топового. Спасибо за подробное описание решения. Надеюсь, что кому-то оно поможет в будущем)

**Comment by st-small** [comment]
@west0r, Алексей, в любом случае, решение уходит на прод, будем тестировать, если нет, допиливать, чтобы работало! Спасибо за SwiftyVK, отличный под получился, в отличии от устаревших доков самого vk!
