### ISSUE TITLE
SwiftyVK is not working with swift version 4

### ISSUE THREAD

**Issue by Priyankadadhich-microlent** [SwiftyVK/SwiftyVK#164]
# 🚫 **ISSUE TEMPLATE** 🚫

🚫 Thanks for using SwiftyVK.

🚫 Support for this project takes a lot of my time. 

🚫 Please, be attentive, fill template and delete this title to let me cope with the issue faster. 

🚫 Issues without filled description, environment and checklist ***will be closed without any comments***

🚫 Thank you for understanding.

---

### Description

Describe the issue in detail here

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx
 Platform version        | exact version e.g. 8.0
 Xcode version           | exact version e.g. 9.0
 Swift version           | exact version e.g. 3.0
 SwiftyVK version        | exact version e.g. 2.0.0
 Integration Method      | e.g. carthage/cocoapods/manually
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [ ] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ ] I made an understandable short title and exhaustive description
* [ ] I attach stack traces or errors description
* [x] I completely describe the environment 
* [ ] I have full filled out this issue template

**Comment by west0r** [comment]
Hello @Priyankadadhich-microlent 

As said in template **Issues without filled description, environment and checklist will be closed without any comments**

Please fill the template and give detailed description of your issue.

P.S: Latest version of library uses Swift 5. Maybe you need older version of library.
