### ISSUE TITLE
SwiftyVK is not working with swift version 4.0

### ISSUE THREAD

**Issue by Priyankadadhich-microlent** [SwiftyVK/SwiftyVK#165]
Hello Everyone,

I used SwiftyVK in my app for perform login from VK, but after install SwiftyVK using Pod, Its seem many error in SwiftyVk library. 
"I used Swift version 4.0"
I attach screenshots of errors
![Screen Shot 2019-06-25 at 5 21 38 PM](https://user-images.githubusercontent.com/52199840/60096402-7cf2e280-976e-11e9-9599-e877cfac032b.png)
![Screen Shot 2019-06-25 at 5 21 57 PM](https://user-images.githubusercontent.com/52199840/60096404-7cf2e280-976e-11e9-930f-9c1f28d94dfa.png)

please looks these images

**Comment by west0r** [comment]
Current SwiftyVK version supports only swift 5. You should use one of previous versions of the library.

**Comment by Priyankadadhich-microlent** [comment]
can you provide me previous version of this library

**Comment by west0r** [comment]
Here are all versions - https://github.com/SwiftyVK/SwiftyVK/releases
