### ISSUE TITLE
Main Thread Checker: UI API called on a background thread

### ISSUE THREAD

**Issue by axenovV** [SwiftyVK/SwiftyVK#169]
### Description
Main Thread Checker: UI API called on a background thread  при вызове метода VK.sessions.default.logIn

У вас контроллер WKWebView инициализируется не на главном треде.

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform version        | exact version e.g. 13.0
 Xcode version           | exact version e.g. 11.0
 Swift version           | exact version e.g. 5.0
 SwiftyVK version        | exact version e.g. 3.4.0
 Integration Method      | e.g. cocoapods

![Снимок экрана 2019-10-10 в 22 27 40](https://user-images.githubusercontent.com/9257530/66600107-72d5e200-ebad-11e9-9ba9-d916e5867b0c.png)

**Comment by west0r** [comment]
Спасибо за репорт!

**Comment by hell4opt** [comment]
что-то вообще перестало работать в принципе :( меил ру видимо поменял что-то

**Comment by axenovV** [comment]
> что-то вообще перестало работать в принципе :( меил ру видимо поменял что-то

Вряд ли, сейчас использую оф. либу, авторизация работает.
