### ISSUE TITLE
Ошибка при авторизации через официальное приложение ВК.

### ISSUE THREAD

**Issue by axenovV** [SwiftyVK/SwiftyVK#170]
### Description

Не работает авторизация через оф. приложение ВК. 

### Текущее поведение
1. VK.sessions.default.logIn
2. Открывается приложение вк
3. Подтверждаем авторизацию
4. Редирект обратно в приложение, которое запрашивало авторизацию.
5. Сыпятся ошибки в лог по поводу #169  
6. Открывается WKWebView.

### Ожидаемое поведение
в делегате получаю токен, без вызова WKWebView.

Подумал, что мб я как-то не так использовал sdk, но проверил Example, там поведение такое же.

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/
 Platform version        | version 13.1
 Xcode version           | version 11.0
 Swift version           | version 5.0
 SwiftyVK version        | version  3.4.0
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues)

**Comment by hell4opt** [comment]
да, на айос 13 открывается веб вью :((( Исправь плиз, задонатим :)

**Comment by west0r** [comment]
Посмотрю в свободное время. Вероятно в ближайший месяц.
