### ISSUE TITLE
Error: invalid scope

### ISSUE THREAD

**Issue by zero-tolerance0** [SwiftyVK/SwiftyVK#174]
### Description
I configured all steps through Readme doc and,
Did get the following error after using first (login) VKApiWorker function, it switched to VK app and then after returning back to my app (inside presented view) as well:
{"error": "invalid_request", "error_description": "invalid scope"}

Here is my info.plist configurations:
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>vk[my-vk-app-id]</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>vkauthorize</string>
				<string>vk-share</string>
				<string>vk</string>
				<string>vk[my-vk-app-id]</string>
			</array>
		</dict>
	</array>

<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>vkauthorize</string>
		<string>vk[my-vk-app-id]</string>
	</array>

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>vk.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>

AppDelegate:
import SwiftyVK

var vkDelegateReference : SwiftyVKDelegate?

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        vkDelegateReference = VKDelegateExample()
        return true
    }

SwiftyVKdelegate.swift:
import UIKit
import SwiftyVK

class VKDelegateExample: SwiftyVKDelegate {
    
    let appId = "[my-vk-app-id]"
    
    let scopes: Scopes = [.messages,.offline,.friends,.wall,.photos,.audio,.video,.docs,.market,.email]
    
    init() {
        VK.setUp(appId: appId, delegate: self)
    }
    
    func vkNeedsScopes(for sessionId: String) -> Scopes {
        // Called when SwiftyVK attempts to get access to user account
        // Should return a set of permission scopes
        return scopes
    }
...
}

Please help.
### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform version        | 11.4
 Xcode version           | 10.2
 Swift version           | 4
 SwiftyVK version        | 3.4.0 Latest release
 Integration Method      | carthage
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x ] I have looked and not find decision at [README.md](./README.md)
* [ x] I have looked and reproduce this behaviour in [Example project](./Example)
* [x ] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [ x] I made an understandable short title and exhaustive description
* [ x] I attach stack traces or errors description
* [ x] I completely describe the environment 
* [ x] I have full filled out this issue template

**Comment by west0r** [comment]
Did you configure your application on VK site? You need to fill bundle ID from your iOS app.

**Comment by zero-tolerance0** [comment]
> Did you configure your application on VK site? You need to fill bundle ID from your iOS app.

Спасибо за ответ. Нет. Заметил что там сейчас нет такого поля куда вставить App Bundle Id в vk.com.
<img width="650" alt="123" src="https://user-images.githubusercontent.com/23029886/70027220-d7208b00-15cb-11ea-99e9-521b7f58c8d5.png">

**Comment by zero-tolerance0** [comment]
> Did you configure your application on VK site? You need to fill bundle ID from your iOS app.

Спасибо за ответ, проблема ушла после того как я создал новое приложение на сайте ВК, и выбрал Standalone-приложение, вместо Встраиваемое приложение. После этого появилось поле куда вставлять bundle ID проекта.
