### ISSUE TITLE
Модальное окно при обновлении token'а

### ISSUE THREAD

**Issue by 0xC01L** [SwiftyVK/SwiftyVK#175]
### Description

Мы используем SwiftyVK только для авторизации пользователя. На следующий день после авторизации, при запуске приложения появляется и сразу исчезает модальное окно с баранкой. Оно появляется во время вызова `VK.API.Users.get`, который мы используем, чтобы обновить имя и аватар пользователя.

Во время этого вызова происходят следующие события:

1) `vkTokenCreated`

2) Появляется ошибка:
2020-01-28 15:19:52.561534+0300 Radio4Me[2043:469488] -canOpenURL: failed for URL: “vkauthorize://authorize?client_id=7188074&scope=4&display=mobile&v5.92&sdk_version=1.3.17&response_type=token&revoke=0” - error: “Не удалось завершить операцию. (OSStatus, ошибка -10814)”

3) `vkNeedToPresent`
4) `vkTokenUpdated`

`VK.API.Users.get` выполняется успешно, но пользователям сложно понять, что за окно появляется на мгновение и сразу исчезает. Даже если в нем будет что-то написано, это все равно не прочитать. Насколько оно требуется и можно ли от него избавиться?

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 12.1.2
 Xcode version           | 11.3
 Swift version           | 5
 SwiftyVK version        | 3.4.1
 Integration Method      | cocoapods
 
  ### Checklist
 
 Check all points of list below and set [x] on each checked point:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [ ] I have looked and reproduce this behaviour in [Example project](./Example)
* [x] I have not find duplicates of this issue in [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x] I made an understandable short title and exhaustive description
* [x] I attach stack traces or errors description
* [x] I completely describe the environment 
* [x] I have full filled out this issue template

**Comment by west0r** [comment]
Скорее всего происходит ошибка считывания токена из кейчейна и окно появляется для апдейта токена через веб вью. 

На переделывание механизма, чтобы не использовать веб вью у меня пока нет ресурсов. 
Нужно понять в чем ошибка с кейчейном.

**Comment by 0xC01L** [comment]
Я думаю дело не в том, что произошла ошибка считывания. Просто токен устарел, так как он действителен лишь в течении 24 часов (как я и написал в описании, что проблема появляется на следующий день).
Раз токен устарел, то SDK будет пытаться его восстановить. И это, как я понял, нормальное поведение. Но, получается, это всегда будет приводить к отображению пустого модального окна?
На этом вебвью нет ничего: лишь белый экран и баранка, и все же оно обязательно для обновления токена?

**Comment by west0r** [comment]
Вк использует oAuth, что подразумевает получение токена через веб вью. 

Когда оно показывается без контента, то это быстрый способ получения токена без запроса прав, конда апп уже был авторизован.

Вариантов фикса вижу несколько

Использовать бесконечный токен
Не использовать быстрое получение токена и всегда показывать запрос прав в вебвью
Пилить костыли, чтобы не показывать веб вью без контента. 

Последний вариант мне не нравится костыльностью и тем, что его поддержка требует бОльшего времени, чем у меня есть. Если он предпочителен, то я буду ждать тех, кто готов за это взяться с моей консультацией по проекту.

Остальные варианты менее инвазивные и более быстрые.

**Comment by 0xC01L** [comment]
> Использовать бесконечный токен
Похоже возвращать `offline` в `vkNeedsScopes` - это лучшее решение для нас. Не могу, правда, понять какие downsides у этого метода.

Спасибо и извините за беспокойство.
