### ISSUE TITLE
Нужен параметр показывающий есть ли сейчас действующая сессия.

### ISSUE THREAD

**Issue by NikKovIos** [SwiftyVK/SwiftyVK#178]
Нужен параметр показывающий есть ли сейчас действующая сессия. Что-то типа:
`hasActiveSession`, для того чтобы не крашилось из-за `"You must call VK.setUp function to start using SwiftyVK!"`

**Comment by NikKovIos** [comment]
#179 
@west0r merge please.

**Comment by west0r** [comment]
Замержено
