### ISSUE TITLE
При отмене алерта перехода не попадает в onError с authorizationCancelled

### ISSUE THREAD

**Issue by NikKovIos** [SwiftyVK/SwiftyVK#182]
SwiftyVK version: 3.4.2
Xcode: 12.5.1

После `VK.sessions.default.logIn` открывается экран

![image](https://user-images.githubusercontent.com/16647690/131019127-f450a169-0d06-4874-949a-30d242056622.png)

Если нажать отмена, то в логах пишется 
```
WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
WF: _WebFilterIsActive returning: NO
```
и в `onError` не заходит с ошибкой.
Как я думаю - должен заходить с .authorizationCancelled.

**Comment by west0r** [comment]
Привет. Спасибо за фидбек. Правильное поведение наверно должно быть таким, но я не помню, реально ли перехватить код ошибки от открытия  VK, вероятно нет. У меня туго со временем сейчас. Если есть возможность - можешь подебажить, что приходит в метод VKAppProxyImpl.handle при отмене и на основе этого бросить ошибку.

Вообще, вроде бы я делал логику, что если апп VK не вернул токен, то вебвью в библиотеке не должна закрываться. Это поведение описано в AuthorizatorImpl.handle. Оно не так у тебя работает?

**Comment by NikKovIos** [comment]
Поправлено в ветке fix-additional-screen-if-app-auth-cancelled в https://github.com/NikKovIos/SwiftyVK.git
Кто хочет может использовать

    pod 'SwiftyVK', :git => 'https://github.com/NikKovIos/SwiftyVK.git', :branch => 'fix-additional-screen-if-app-auth-cancelled'

**Comment by west0r** [comment]
@NikKovIos не хочешь сделать пулл реквест?

**Comment by NikKovIos** [comment]
@west0r лови https://github.com/SwiftyVK/SwiftyVK/pull/183

**Comment by NikKovIos** [comment]
@west0r вольёшь?

**Comment by NikKovIos** [comment]
Влито
