### ISSUE TITLE
Либа мертва?

### ISSUE THREAD

**Issue by NikKovIos** [SwiftyVK/SwiftyVK#185]
Здравствуйте, подскажите будут ли обновления данной либы или стоит искать аналог?

**Comment by west0r** [comment]
Здравствуйте. В чем именно вопрос и какие обновления нужны?

**Comment by NikKovIos** [comment]
Правки issue и вливания pull request.

**Comment by west0r** [comment]
Я код не пишу в библиотеку, но слежу за ней и pull request'ы вливаю, если они есть

**Comment by NikKovIos** [comment]
Тогда вот:

https://github.com/SwiftyVK/SwiftyVK/pull/184/files
https://github.com/SwiftyVK/SwiftyVK/pull/183/files
https://github.com/SwiftyVK/SwiftyVK/pull/177

**Comment by west0r** [comment]
Два твоих ПРа вмержил. https://github.com/SwiftyVK/SwiftyVK/pull/177 нет. В нем описано почему и что прошу

**Comment by NikKovIos** [comment]
Огонь, спасибо!👌🏻😃🙌🏻
