### ISSUE TITLE
Смена пользователя

### ISSUE THREAD

**Issue by Ironrnd** [SwiftyVK/SwiftyVK#31]
При первой авторизации VK.logIn() выходит модальное окно с приглашение ввести логин и пароль. Все отлично работает. После вызова метода VK.logOut() - запросы возвращают ошибку авторизации - тоже все в норме. 
Однако, при следующем вызове метода VK.logIn() выходит окно только со списком разрешений для приложения. И нет возможности сменить пользователя. 
Подскажите, каким образом сделать выход из авторизации с возможностью смены пользователя?

**Comment by WE-St0r** [comment]
Исправлено

**Comment by Vladossik** [comment]
Добрый вечер, столкнулась с такой же проблемой, но уже в 2019 году.

**Comment by west0r** [comment]
@Vladossik приложите, пожалуйста, скриншот после повторного вызова `VK.logIn()`. У вас точно список разрешений без возможности сменить пользователя? Должно быть вот так 
<img width="487" alt="Screenshot 2019-04-21 at 18 23 04" src="https://user-images.githubusercontent.com/8268115/56472057-8d32cc80-6462-11e9-8131-2502f30d5f5b.png">
Предлагается войти тем же пользователем, так как iOS сохранила куки для него, но сменить пользователя можно.

И подскажите, пожалуйста, версию библиотеки.

**Comment by Vladossik** [comment]
После того, как я разлогинилась и пытаюсь зайти заново, то он переходит в приложение Вконтакте и просить разрешить:[Image] После если нажать отмену, то он показывает экран: [Image]   Но периодически он показывал вместо логина/пароля экран с разрешением, как и в приложении(первый скрин). Я починила этот баг своим методом, чтобы в вьюшке, которая открывается вебовская он сбрасывал данные после нажатия на logout.

Установить Outlook для iOS<https://aka.ms/o0ukef>

________________________________
От: Alexey Kudryavtsev <notifications@github.com>
Отправлено: воскресенье, апреля 21, 2019 6:25 ПП
Кому: SwiftyVK/SwiftyVK
Копия: Вакуленко Владислава Витальевна; Mention
Тема: Re: [SwiftyVK/SwiftyVK] Смена пользователя (#31)


@Vladossik<https://github.com/Vladossik> приложите, пожалуйста, скриншот после повторного вызова VK.logIn(). У вас точно список разрешений без возможности сменить пользователя? Должно быть вот так
[Screenshot 2019-04-21 at 18 23 04]<https://user-images.githubusercontent.com/8268115/56472057-8d32cc80-6462-11e9-8131-2502f30d5f5b.png>
Предлагается войти тем же пользователем, так как iOS сохранила куки для него, но сменить пользователя можно.

И подскажите, пожалуйста, версию библиотеки.

**Comment by west0r** [comment]
@Vladossik спасибо за информацию, но хотелось бы больше немного получить. В сообщении отсутствуют скриншоты, которые там были, но не вставились. И как починили?

Скажите, пожалуйста, в чем проблема показа экрана с разрешениями, когда можно сменить пользователя? В прошлый раз проблема была в том, что пользователя сменить было невозможно и это правда критично. Ваш кейс для меня пока остается непонятен.

**Comment by west0r** [comment]
@Vladossik ping

**Comment by west0r** [comment]
@Vladossik закрываю issue, так как не дождался от вас ответа в течении двух месяцев.
