### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by bumsun** [SwiftyVK/SwiftyVK#60]
Спасибо за библиотеку. Все отлично работает на эмуляторе и моем устройстве, но приложение второй раз отклонили по причине креша при авторизации в ВК. Логи, которые присылает Apple косвенно намекают, что это связанно с вашей библиотекой. Они тесты проводят в IPV6 сети. Возможно ваша библиотека, не работает в IPV6. Если я что-то не так понял, то прошу совета. Заранее благодарю :)

**Comment by WE-St0r** [comment]
Приветствую. Есть вот такой вот баг у VK SDK - https://github.com/VKCOM/vk-ios-sdk/issues/472. Пока не ясно в чем проблема. Вопрос в том, почему происходит креш. Есть ли какие-то более детальные логи?

**Comment by WE-St0r** [comment]
Попробую в свободное время поднять 6to4  туннель. Посмотреть, что происходит. На это потребуется некоторое время)

**Comment by PsssUm** [comment]
Добрый день, получилось что-нибудь выяснить по данной ошибке?

**Comment by WE-St0r** [comment]
К сожалению пока нет. Мне не удалось нормально поднять IPv6 сеть у своего провайдера и воспроизвести проблему.

**Comment by PsssUm** [comment]
Привет, мне удалось поднять IPv6 и воспроизвести проблему, есть логи из xcode:
4/8, 17:00:15: Token ~ getting
4/8, 17:00:15: Token ~  not saved yet in storage
4/8, 17:00:15: Global ~ SwiftyVK configured
4/8, 17:00:15: LongPoll ~ Stopped
4/8, 17:00:15: Token ~ removed
4/8, 17:00:15: Token ~ getting
4/8, 17:00:15: Token ~  not saved yet in storage
SwiftyVK: authorize
4/8, 17:00:16: WebPresenter ~ start
objc[22253]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x12882f998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x128651880). One of the two will be used. Which one is undefined.
4/8, 17:00:16: WebController ~ load https://oauth.vk.com/authorize?client_id=5292546&scope=335890&display=mobile&v5.62&sdk_version=1.3.17&response_type=token&revoke=1
4/8, 17:00:17: WebPresenter ~ handle error SwiftyVKAuthError[4]: nil
4/8, 17:00:17: WebController ~ load https://oauth.vk.com/authorize?client_id=5292546&scope=335890&display=mobile&v5.62&sdk_version=1.3.17&response_type=token&revoke=1
4/8, 17:00:17: WebPresenter ~ handle error SwiftyVKAuthError[4]: nil
4/8, 17:00:17: WebController ~ load https://oauth.vk.com/authorize?client_id=5292546&scope=335890&display=mobile&v5.62&sdk_version=1.3.17&response_type=token&revoke=1
4/8, 17:00:17: WebPresenter ~ handle error SwiftyVKAuthError[4]: nil
4/8, 17:00:17: WebController ~ load https://oauth.vk.com/authorize?client_id=5292546&scope=335890&display=mobile&v5.62&sdk_version=1.3.17&response_type=token&revoke=1
4/8, 17:00:17: WebPresenter ~ handle error SwiftyVKAuthError[4]: nil
4/8, 17:00:17: WebController ~ load https://oauth.vk.com/authorize?client_id=5292546&scope=335890&display=mobile&v5.62&sdk_version=1.3.17&response_type=token&revoke=1
4/8, 17:00:17: WebPresenter ~ handle error SwiftyVKAuthError[4]: nil
4/8, 17:00:17: WebController ~ hide
4/8, 17:00:18: WebPresenter ~ finish
Autorization failed with error: 
error SwiftyVKAuthError[4]: nil
Можно ли включить как-то более подробные логи? Плюс ко всему при подключении к IPv6 сети, не получается даже через браузер зайти на вк, да и в общем на гитхаб тоже)

**Comment by WE-St0r** [comment]
@PsssUm, это полные логи. Можно посмотреть, что происходит в WebController, но думаю, что это ничего не даст, так как тут видно, что он несколько раз безуспешно пытается открыть страницу авторизации.

Возможно vk просто не поддерживает IPv6. По крайней мере, в ходе экспериментов, я не смог залукапить их IPv6 адреса. Так же [этот ресурс](https://mxtoolbox.com/SuperTool.aspx?action=aaaa%3avk.com&run=toolpage) говорит, что поддержки нет. У гитхаба и эпла, кстати, тоже.

**Comment by voody2506** [comment]
Покопался, раньше были временные отключения IPv6, а теперь VK полностью его отключил!
И включит ли поддержку данного протокола повторно, неизвестно.

Остается вопрос, а как, собственно, проходить проверку?

**Comment by WE-St0r** [comment]
Да, у вконтакте на данный момент нет поддержки IPV6. Данных, планируется ли она нет. К сожалению, нам пока придется жить с этим. :(

**Comment by ArmenuhiM** [comment]
Hi everyone, it means we can not submit the app on AppStore which use VK SDK ?

**Comment by west0r** [comment]
@ArmenuhiM no, Apple not always test and reject apps without ipv6 support.

**Comment by ArmenuhiM** [comment]
@west0r Ok, thanks for the answer.

**Comment by west0r** [comment]
@bumsun @PsssUm @ArmenuhiM @voody2506 были ли за последнее время проблемы с отклонениями из-за IPv6? В VKCOM/vk-ios-sdk#472 сообщают, что проблему решили.

**Comment by west0r** [comment]
Так как обращений по проблема нет ни тут, ни в VK SDK, то закрываю issue, как неактуальное.

Всем спасибо за фидбек.
