### ISSUE TITLE
Разные замечания

### ISSUE THREAD

**Issue by NikKovIos** [SwiftyVK/SwiftyVK#69]
Дабы улучшить библиотеку, буду писать здесь фидбек, по поводу того, какие вопросы и трудности встречались по ходу использования.
Если данная тема не интересна - просто закройте её и я не буду создавать новые)

**Comment by NikKovIos** [comment]
`func vkShouldUseTokenPath() -> String? { return "" }`  
Приходится писать эту строку в классе, ответственным за VKDelegate. По меркам swift 3 это не красиво. Но главное - не понятно, будет ли данная заглушка на что-то влиять или нет?

**Comment by NikKovIos** [comment]
Сейчас в свифте 3 используется метод `func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool` вместо `func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool`  

В SDK есть метод  `VK.process(url: url, sourceApplication: callingAppName)`. Чтобы его использовать, нужно делать примерно следующее:  

    if let callingAppName = options[UIApplicationOpenURLOptionsKey.sourceApplication] as? String {            
      VK.process(url: url, sourceApplication: callingAppName)
    }

Хотелось бы иметь метод потипу как у фейсбука `        SDKApplicationDelegate.shared.application(app, open: url, options: options)`

**Comment by west0r** [comment]
Сейчас я делаю большой рефакторинг библиотеки в котором перерабатываются внутренние концепции и внешний интерфейс.

Функция `vkShouldUseTokenPath()` - легаси, которого в следующей версии уже не будет.  Оставлена именно для обратной совместимости версии 2 к 1.

По поводу `VK.process(url: url, sourceApplication: callingAppName)` я посмотрю что можно улучшить. 

Использовать вк и фейсбук можно вместе. Просто добавляйте код одной из библиотек в функции AppDelegate друг за другом. Они не взаимоисключающие.

**Comment by west0r** [comment]
На самом деле лучше на одну проблему создавать один issue. Так мне потом проще отслеживать, что сделано, а что еще нужно. Это более наглядно.

**Comment by NikKovIos** [comment]
Окей, как скажешь - буду создавать issue :)
