### ISSUE TITLE
Swift 4 JSONDecoder

### ISSUE THREAD

**Issue by ilyakooo0** [SwiftyVK/SwiftyVK#70]
You should really look into returning the response of a request in a swift native type rather than a SwiftyJSON object. 

I am proposing this because:
1. The framework will become a plot more usable and swifty
2. It will most definitely be much better at performance.

Most of the processing done in my app is processing of JSON in this framework.

If you don't have the time/motivation to implement it yourself I can try to do it myself.

**Comment by west0r** [comment]
Thanks for your comment. I myself do not like the dependence on SwiftyJSON, but swift decoders have [not fully implemented](https://github.com/apple/swift-evolution/blob/master/proposals/0167-swift-encoders.md) yet and I can not use them. Now I'm actively working on the next version of SwiftyVK. I think I can use it in the future.

**Comment by ilyakooo0** [comment]
А что не работает то?
В Swift 4 уже рабочая версия

**Comment by west0r** [comment]
По крайней мере в том пропозле не указано, что он реализован.

Ага, есть еще вот [такой](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md). Написано, что реализован. Значит можно будет использовать.

Я не уверен, что это изменение войдет в SwiftyVK 2.x. Скорей всего уже в 3.0. Сейчас эта версия в стадии активной разработки. Я не уверен, что она увидит свет раньше конца лета, но по крайней мере к релизу 4 свифта должна быть готова.

**Comment by west0r** [comment]
JSONDecoder - слишком узкая реализация. Реализован возврат Data, который можно парсить как угодно
