### ISSUE TITLE
Authorizator or LogIn() should use escaping closure for easier data access

### ISSUE THREAD

**Issue by outbools** [SwiftyVK/SwiftyVK#75]
### New Issue Checklist

* [x] I have looked at the [README.md](./README.md)
* [x] I have looked at the [Example project](./Example)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
----------------------|-------------------------------------|
  Swift Version         | 3.1

 
### Issue Description

Consider the official Facebook Swift SDK - https://developers.facebook.com/docs/swift/login
```
// Once the button is clicked, show the login dialog

@objc func loginButtonClicked() {
  let loginManager = LoginManager()
  loginManager.logIn([ .PublicProfile ], viewController: self) { loginResult in
    switch loginResult {
    case .Failed(let error): 
      print(error)
    case .Cancelled:
      print("User cancelled login.")
    case .Success(let grantedPermissions, let declinedPermissions, let accessToken):
      print("Logged in!")  }
```

What im suggesting is implement auth states handling based on `@escaping` enum variable for easier data access (loginResult in Facebook example)

**Comment by west0r** [comment]
Done
