### ISSUE TITLE
Getting raw response data / using different JSON parsing library

### ISSUE THREAD

**Issue by ilyakooo0** [SwiftyVK/SwiftyVK#76]
Is there a way to get raw response data without converting to into the SwiftyJSON format? 

I am asking for performance reasons. SwiftyJSON is one of the slowest Swift JSON parsing libraries and my app gets a significant performance hit because of it. 

I would recommend you use [Marshal](https://github.com/utahiosmac/Marshal) or [Decodable](https://github.com/Anviking/Decodable).

Is there a way for me to tell SwiftyVK not to convert everything to SwiftyJSON and just give me back the raw data response from the request, preferably still catching errors, do that I can parse it any way I want?

Source: https://github.com/bwhiteley/JSONShootout#performance.

**Comment by west0r** [comment]
I know about this performance comparison.  Now SwiftyVK is tightly bound to SwiftyJSON. As I said in the #70, the changes will be in the next version of SwiftyVK.

**Comment by west0r** [comment]
Реализовано
