### ISSUE TITLE
Get LongPoll Server

### ISSUE THREAD

**Issue by Amekill** [SwiftyVK/SwiftyVK#89]
### New Issue Checklist

* [+] I have looked at the [README.md](./README.md)
* [+] I have looked at the [Example project](./Example)
* [+] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | All
  Swift Version          | 4
 SwiftyVK Version        | последняя
 Integration Method      | carthage
 
### Issue Description
Вызов метода messages.getLongPollServer должен срабатывать только 1 раз и только при старте, а не при сворачивании/разворачивании, сейчас идет просто лишняя нагрузка на запросы.

**Comment by west0r** [comment]
Спасибо за фидбек, изменю поведение в новой мажорной версии. С изменениями в публичном интерфейсе можете ознакомиться в ветке v3.

**Comment by west0r** [comment]
Я еще не проверял картаж на новой версии. Спасибо, проверю в ближайшее время)

**Comment by Amekill** [comment]
@west0r и вам спасибо )

**Comment by west0r** [comment]
Готово

**Comment by Amekill** [comment]
@west0r а добавление параметров к хранимой процедуре как-то по-другому теперь добавляется или баг v3?
<img width="503" alt="screen shot 2017-10-22 at 10 55 39 am" src="https://user-images.githubusercontent.com/27199647/31859674-a8c204c4-b717-11e7-9075-ab97f8c0d4c5.png">

**Comment by west0r** [comment]
@Amekill так много переделывал, что на этот момент не обратил внимание. Поправлю.

P.S.: Лучше заводи плиз отдельный issue на разные вопросы/пробелемы. Так трекать потом удобнее)

**Comment by Amekill** [comment]
@west0r Без проблем, спасибо )

**Comment by west0r** [comment]
Запушил
