### ISSUE TITLE
Авторизация oAuth

### ISSUE THREAD

**Issue by Amekill** [SwiftyVK/SwiftyVK#93]
### Description

oAuth авторизация невозможна, если отсутствует официальный клиент. При попытке авторизоваться, после ввода логина и пароля на долю секунды перекидывает на подтверждение двухфакторной авторизации и возвращает обратно на ввод логина и пароля, затем можно можно бесконечно нажимать на кнопку входа (даже при пустых полях) и будет на долю секунды кидать на страницу ввода кода двухфакторки, а в личные сообщения будет бесконечно приходить один тот же код.

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform version        | 11.1
 Xcode version           | 9.1
 Swift version           | 4.0.1
 SwiftyVK version        | 3.0
 Integration Method      | carthage
 
 ### Checklist
 
* [X] I have looked and not find decision at [README.md](./README.md)
* [X] I have looked and not find decision at [Example project](./Example)
* [X] I have not find duplicates of this issue on [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [X] I made an understandable short title
* [X] I made an exhaustive description
* [X] I completely described the environment 
* [X] I have full filled out this issue template
* [x] I use english language

**Comment by west0r** [comment]
Починю в ближайшее время

**Comment by ordinec7** [comment]
При отсутствующем официальном клиенте webview не открывается вообще. В логах вот такая ошибка - 
canOpenURL: failed for URL: "vkauthorize://authorize?client_id=(xxxxxxxxx)&scope=4259840&display=mobile&v5.69&sdk_version=1.3.17&response_type=token&revoke=1" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
