### ISSUE TITLE
[Предложение] Свои параметры метода

### ISSUE THREAD

**Issue by Amekill** [SwiftyVK/SwiftyVK#94]
Было бы неплохо добавить возможность добавления/написания своих параметров к методу запроса, т.к. сейчас единственный вариант - добавление их непосредственно через исходный код SwiftyVK.

**Comment by west0r** [comment]
Посмотрю что можно сделать в этом направлении. Изначально задумывалось, что все должно быть через енам, но тут речь видимо про свои методы, верно?

**Comment by Amekill** [comment]
Да, которые создаются через хранимые процедуры
