### ISSUE TITLE
Документация очень сильно устаревшая

### ISSUE THREAD

**Issue by Raserad** [SwiftyVK/SwiftyVK#96]
Документация представленная здесь не соответствует swiftyvk. Во первых не работает VK.set() во вторых не нет такого протокола как swiftyvkdelegate а есть протокол vkdelegate.

**Comment by west0r** [comment]
Здравствуйте, документация была полностью переписана 9 дней назад. Она свежайшая. 
Если вы используете версию SwiftyVK меньше 3.0, то тут есть более старая версия - https://github.com/SwiftyVK/SwiftyVK/tree/e025caa9c30311cd289aef22653c58247ea71f77
