### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by Amekill** [SwiftyVK/SwiftyVK#99]
### Description

В блоке ошибок при выводе через `print(error)` отображается вся информация об ошибке, но если пытаться достать ее код (`print (error.localizedDescription)`), то он всегда получается 1 (видно на скрине). Каким образом можно получать код ошибки ?
<img width="1155" alt="screen shot 2017-10-27 at 5 41 41 pm" src="https://user-images.githubusercontent.com/27199647/32109853-933f0798-bb3e-11e7-9de3-7e4cf553c11a.png">

### Environment

 Key                     | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform version        | 11.1
 Xcode version           | 9.1
 Swift version           | 4
 SwiftyVK version        | 3.0
 Integration Method      | carthage
 
 ### Checklist
 
 Set [x] in box if you checked this:
 
* [x] I have looked and not find decision at [README.md](./README.md)
* [x] I have looked and not find decision at [Example project](./Example)
* [x] I have not find duplicates of this issue on [issues list](https://github.com/west0r/SwiftyVK/issues) 
* [x] I made an understandable short title
* [x] I made an exhaustive description
* [x] I completely described the environment 
* [x] I have full filled out this issue template
* [x] I use english language

**Comment by west0r** [comment]
`localizedDescription` пока еще не завез, но даже когда он будет, то не факт, что через него можно будет взять правильный код.  Наиболее валидный способ:
```
switch error {
case let .api(apiError):
    print(apiError.code)
default:
    print(error)
}
```

**Comment by Amekill** [comment]
@west0r Спасибо, это помогло. Нашел еще одну ошибку - если отключен интернет полностью, то не выводит никакой ошибки

**Comment by west0r** [comment]
@Amekill тестировал на iOS 11? Если да, то тут используется параметр `URLSessionConfiguration` `waitsForConnectivity`, который заставляет соединение ждать появление интернета. 

Использовал эту фичу в качестве эксперимента. Если будут какие-то проблемы с ней, то пишите.

**Comment by Amekill** [comment]
@west0r Это конечно круто (и вроде даже работает), но возможно ли давать возможность выбора?

**Comment by west0r** [comment]
@Amekill уже думал об этом. В ближайших обновлениях добавлю такую возможность. Спасибо за фидбек.
